### PR TITLE
add java version

### PR DESCRIPTION
**Pull request by Starlight220**
still needs to have a way to get the timestamp through JNI

### CODE REVIEW

**Comment by PeterJohnson** [comment]
There needs to be a class per datatype.  E.g. DoubleLog etc.

**Comment by Starlight220** [comment]
ok, will add today! Is inheritance preferable or is generics?

**Comment by PeterJohnson** [comment]
Generics are a performance killer.  In particular we want appending a number to the log to be very fast, which means non-boxed natives.

**Comment by Starlight220** [comment]
So we're going with inheritance?

**Comment by Starlight220** [comment]
Perhaps only byte logging should go through JNI and everything else will be converted?

**Pull request merged**
